name: Generate Directory Listing
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install http-server
      run: npm install http-server -g
      
    - name: Generate Directory Listing to index.html
      run: |
        echo "<html><body><ul>" > index.html
        find * -type d -exec echo "<li><a href='{}'>{}</a></li>" \; >> index.html
        find * ! -name "index.html" -type f -exec echo "<li><a href='{}'>{}</a></li>" \; >> index.html
        echo "</ul></body></html>" >> index.html
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: './'
