name: Deploy GitHub Pages

on: 
  schedule:
    - cron:  '0 0 * * *' # 每天在UTC时间午夜触发
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Add your setup steps if needed

    - name: Generate index.html
      run: |
        echo "<!DOCTYPE html>" > index.html
        echo "<html><head><title>My Project</title></head><body>" >> index.html
        echo "<h1>Welcome to My Project</h1>" >> index.html
        echo "<ul>" >> index.html
        for file in *; do
          echo "<li><a href='$file'>$file</a></li>" >> index.html
        done
        echo "</ul>" >> index.html
        echo "</body></html>" >> index.html

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: . # The folder the action should deploy.
